# transparency
background_opacity 0.80

# blur (works in Hyprland)
background_blur 20

# better font rendering
confirm_os_window_close 0

# cursor
cursor_shape beam
cursor_blink_interval 0.5

#just an another set up
foreground #00ff00
background #000000
cursor #00ff00

#urekka bin bin boo just for zsh
shell /bin/zsh

#just A fontt
font=MesloLGS Nerd Font:size=12
